"""TraceForge 固定默认值。

集中保存上下文预算、自动验证重试和 Web 端口等运行边界，
避免重要参数散落在各个模块中。
"""

DEFAULT_MAX_STEPS = 20
DEFAULT_COMMAND_TIMEOUT = 30
DEFAULT_MAX_TOOL_OUTPUT = 8000
DEFAULT_MAX_HISTORY_TURNS = 8
DEFAULT_MAX_CONTEXT_CHARS = 48000
DEFAULT_CONDENSED_SUMMARY_CHARS = 6000
DEFAULT_VERIFICATION_RETRIES = 2

DEFAULT_READ_LINE_COUNT = 200
MAX_READ_LINE_COUNT = 400

DEFAULT_WEB_HOST = "127.0.0.1"
DEFAULT_WEB_PORT = 8765
